version: "3.9"
services:
  mysql_service:
    container_name: mysql_service
    build: ./mysql
    ports:
      - "6603:3306"
  mysql_api:
    container_name: mysql_api_container
    build: ./mysql
    ports:
      - "5001:5001"
  data_crawling:
    container_name: data_crawling
    build: ./data_crawling
    ports:
      - "5000:5000"
    depends_on:
      - mysql_api